### ISSUE TITLE
Description

### ISSUE THREAD

**Issue by drhouse** [shagabutdinov/sublime-named-mark#1]
C'mon, I've rarely seen such lazy explanations for a plugin:
"A bit smarter marks than default."
"There a bit more features. Check source code to find out all of it."

Set, mark, select, destroy... In the animation you can't see anything that regular marks don't already do.

**Comment by shagabutdinov** [comment]
Man, I checked your account, you did literally nothing and you are walking and complaining around. If you are unsatisfied with explanations - you can ask questions and than open a pull request to fix the description.

**Comment by drhouse** [comment]
Woah check out the detective, here buddy, I've written lots of opensource scripts with plenty of downloads, have fun eating your words:
https://greasyfork.org/en/users/10118-drhouse?sort=total_installs

I'm giving you fair criticism from experience, your descriptions suck, Go read mine since you want to compare. it's never the users job to look through source code to figure out what a simple sublime plugin is supposed to do.

**Comment by shagabutdinov** [comment]
Ok, good for you. If you don't like my descriptions, just don't read it.
It'll be simpler for both of us.

## 

Leonid Shagabutdinov,
+7 905 937 6988
